// apps/react-app/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import { usePoiStore } from './store/poi.store';
import { useMapLibre } from './hooks/useMapLibre';
import { useFileIo } from './hooks/useFileIo';
import {
  TopBar, Sidebar, POIFormModal,
  type POIFormData,
} from '@geo-editor/ui-react';
import { ImportReport } from './components/ImportReport';
import { toCategoryId, CATEGORY_ICONS, SIDEBAR_CATEGORIES } from './utils/categoryMap';
import type { ImportResult, PoiFeature, LngLat } from '@geo-editor/core';
import 'maplibre-gl/dist/maplibre-gl.css';

export default function App() {

  const mapContainer = useRef<HTMLDivElement>(null);

  const {
    restore, filteredFeatures, collection, selectedId,
    loadCollection, selectPoint, removePoint, setFilter,
    undo, redo, canUndo: getCanUndo, canRedo: getCanRedo,
    clearAll, addPoint, updatePoint, features,
  } = usePoiStore();

  const history = usePoiStore(s => s.history);

  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [search, setSearch]                     = useState('');
  const [showForm, setShowForm]                 = useState(false);
  const [pendingCoords, setPendingCoords]       = useState<LngLat | null>(null);
  const [editingPoi, setEditingPoi]             = useState<PoiFeature | null>(null);
  const [importResult, setImportResult]         = useState<ImportResult | null>(null);

  const { updateData, flyTo, highlightPoi } = useMapLibre(mapContainer, (coords) => {
    setPendingCoords(coords);
    setEditingPoi(null);
    setShowForm(true);
  });

  const { importGeoJson, exportGeoJson } = useFileIo();

  useEffect(() => { restore(); }, []);
  useEffect(() => { updateData(collection()); }, [history, updateData]);
  useEffect(() => { highlightPoi(selectedId); }, [selectedId, highlightPoi]);

  function handleSearchChange(value: string) {
    setSearch(value);
    setFilter({ query: value });
  }

  async function handleImport(file: File) {
    try {
      const result = await importGeoJson(file);
      if (result.imported.length > 0) {
        loadCollection({
          type: 'FeatureCollection',
          features: [...collection().features, ...result.imported],
        });
      }
      setImportResult(result);
    } catch (err) {
      console.error('Import failed:', err);
    }
  }

  function handleExport() { exportGeoJson(collection()); }
  function handleUndo()   { undo(); }
  function handleRedo()   { redo(); }

  async function handleClearAll() {
    if (confirm('¿Borrar todos los puntos y reiniciar?')) {
      await clearAll();
    }
  }

  function handleEditRequest(poi: PoiFeature) {
    setEditingPoi(poi);
    setPendingCoords(null);
    setShowForm(true);
  }

  function handleDeleteRequest(id: string) {
    const poi = features().find(f => String(f.id) === id);
    if (poi && confirm(`¿Eliminar "${poi.properties.name}"?`)) {
      removePoint(poi.id!);
    }
  }

  function handleFocusPoi(id: string) {
    selectPoint(id);
    const poi = features().find(f => String(f.id) === id);
    if (poi) {
      const [lng, lat] = poi.geometry.coordinates;
      flyTo(lng, lat);
    }
  }

  function handleNewPoi() {
    setPendingCoords(null);
    setEditingPoi(null);
    setShowForm(true);
  }

  function handleFormCancel() {
    setShowForm(false);
    setEditingPoi(null);
    setPendingCoords(null);
  }

  function handleFormSave(data: POIFormData) {
    if (editingPoi) {
      updatePoint(editingPoi.id!, {
        name:        data.name,
        category:    data.category,
        description: data.description,
      });
    } else if (pendingCoords || (data.lat && data.lng)) {
      const coords = pendingCoords ?? { lat: parseFloat(data.lat), lng: parseFloat(data.lng) };
      if (!isNaN(coords.lat) && !isNaN(coords.lng)) {
        addPoint(coords, data.name, data.category, data.description);
      }
    }
    setShowForm(false);
    setEditingPoi(null);
    setPendingCoords(null);
  }

  const allPois    = filteredFeatures();
  const mappedPois = allPois.map(f => ({
    id:       String(f.id),
    name:     f.properties.name,
    category: toCategoryId(f.properties.category),
    icon:     CATEGORY_ICONS[toCategoryId(f.properties.category)],
    lat:      f.geometry.coordinates[1],
    lng:      f.geometry.coordinates[0],
    selected: selectedId === f.id,
  }));

  const modalInitialData = editingPoi
    ? {
        id:          String(editingPoi.id),
        name:        editingPoi.properties.name,
        category:    toCategoryId(editingPoi.properties.category),
        lat:         editingPoi.geometry.coordinates[1].toString(),
        lng:         editingPoi.geometry.coordinates[0].toString(),
        description: editingPoi.properties.description ?? '',
      }
    : pendingCoords
      ? {
          name:        '',
          category:    'custom' as const,
          lat:         pendingCoords.lat.toString(),
          lng:         pendingCoords.lng.toString(),
          description: '',
        }
      : undefined;

  return (
    <div className="app-shell">
      <TopBar
        search={search}
        onSearchChange={handleSearchChange}
        onImport={handleImport}
        onExport={handleExport}
        onUndo={handleUndo}
        onRedo={handleRedo}
        canUndo={getCanUndo()}
        canRedo={getCanRedo()}
        onClearAll={handleClearAll}
      />

      <ImportReport result={importResult} onDismiss={() => setImportResult(null)} />

      <div className="app-body">
        <Sidebar
          pois={mappedPois}
          categories={SIDEBAR_CATEGORIES}
          collapsed={sidebarCollapsed}
          onToggle={() => setSidebarCollapsed(c => !c)}
          onNew={handleNewPoi}
          onEdit={poi => handleEditRequest(features().find(f => String(f.id) === poi)!)}
          onDelete={handleDeleteRequest}
          onFocus={handleFocusPoi}
        />
        <div ref={mapContainer} className="app-map" />
      </div>

      <POIFormModal
        open={showForm}
        initialData={modalInitialData}
        onClose={handleFormCancel}
        onSave={handleFormSave}
      />
    </div>
  );
}

// apps/angular-app/src/app/app.component.ts
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { PoiService } from './core/services/poi.service';
import { MapService } from './core/services/map.service';
import { FileIoService } from './core/services/file-io.service';
import { MapComponent } from './features/map/map.component';
import { ImportReportComponent } from './shared/components/import-report/import-report.component';
import { DsTopBarComponent, DsSidebarComponent, DsPoiFormModalComponent, type PoiFormData, type SidebarPoi, type SidebarCategory } from '@geo-editor/ui-angular';
import { toCategoryId, SIDEBAR_CATEGORIES } from './utils/category-map';
import type { ImportResult, PoiFeature, LngLat } from '@geo-editor/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  standalone: true,
  imports: [
    MapComponent,
    ImportReportComponent,
    DsTopBarComponent,
    DsSidebarComponent,
    DsPoiFormModalComponent,
  ],
})
export class AppComponent implements OnInit {
  readonly poiSvc = inject(PoiService);
  private readonly mapSvc     = inject(MapService);
  private readonly fileIoSvc  = inject(FileIoService);

  readonly sidebarCollapsed = signal(false);
  readonly search           = signal('');
  readonly showForm         = signal(false);
  readonly pendingCoords    = signal<LngLat | null>(null);
  readonly editingPoi       = signal<PoiFeature | null>(null);
  readonly importResult     = signal<ImportResult | null>(null);

  readonly SIDEBAR_CATEGORIES = SIDEBAR_CATEGORIES;

  readonly mappedPois = computed(() => {
    const allPois = this.poiSvc.filteredFeatures();
    return allPois.map(f => ({
      id:       String(f.id),
      name:     f.properties.name,
      category: toCategoryId(f.properties.category),
      lat:      f.geometry.coordinates[1],
      lng:      f.geometry.coordinates[0],
      selected: this.poiSvc.selectedId() === f.id,
    } as SidebarPoi));
  });

  readonly modalInitialData = computed(() => {
    const editingPoi    = this.editingPoi();
    const pendingCoords = this.pendingCoords();

    if (editingPoi) {
      return {
        id:          String(editingPoi.id),
        name:        editingPoi.properties.name,
        category:    toCategoryId(editingPoi.properties.category),
        lat:         editingPoi.geometry.coordinates[1].toString(),
        lng:         editingPoi.geometry.coordinates[0].toString(),
        description: editingPoi.properties.description ?? '',
      };
    }

    if (pendingCoords) {
      return {
        name:        '',
        category:    'custom' as const,
        lat:         pendingCoords.lat.toString(),
        lng:         pendingCoords.lng.toString(),
        description: '',
      };
    }

    return undefined;
  });

  async ngOnInit(): Promise<void> {
    await this.poiSvc.restore();
  }

  onMapClick(coords: LngLat): void {
    this.pendingCoords.set(coords);
    this.editingPoi.set(null);
    this.showForm.set(true);
  }

  onSearchChange(query: string): void {
    this.search.set(query);
    this.poiSvc.setFilter({ query });
  }

  async onImport(file: File): Promise<void> {
    try {
      const result = await this.fileIoSvc.importGeoJson(file);
      if (result.imported.length > 0) {
        const collection = this.poiSvc.collection();
        this.poiSvc.loadCollection({
          type: 'FeatureCollection',
          features: [...collection.features, ...result.imported],
        });
      }
      this.importResult.set(result);
    } catch (err) {
      console.error('Import failed:', err);
    }
  }

  onExport(): void {
    this.fileIoSvc.exportGeoJson(this.poiSvc.collection());
  }

  onUndo(): void  { this.poiSvc.undo(); }
  onRedo(): void  { this.poiSvc.redo(); }

  async onClearAll(): Promise<void> {
    if (confirm('¿Borrar todos los puntos y reiniciar?')) {
      await this.poiSvc.clearAll();
    }
  }

  onNewPoi(): void {
    this.pendingCoords.set(null);
    this.editingPoi.set(null);
    this.showForm.set(true);
  }

  onEditById(id: string): void {
    const poi = this.poiSvc.features().find(f => String(f.id) === id);
    if (poi) {
      this.editingPoi.set(poi);
      this.pendingCoords.set(null);
      this.showForm.set(true);
    }
  }

  onDeletePoi(id: string): void {
    const poi = this.poiSvc.features().find(f => String(f.id) === id);
    if (poi && confirm(`¿Eliminar "${poi.properties.name}"?`)) {
      this.poiSvc.removePoint(poi.id!);
    }
  }

  onFocusPoi(id: string): void {
    this.poiSvc.selectPoint(id);
    const poi = this.poiSvc.features().find(f => String(f.id) === id);
    if (poi) {
      const [lng, lat] = poi.geometry.coordinates;
      this.mapSvc.flyTo(lng, lat);
    }
  }

  onModalClose(): void {
    this.showForm.set(false);
    this.editingPoi.set(null);
    this.pendingCoords.set(null);
  }

  onModalSave(data: PoiFormData): void {
    if (this.editingPoi()) {
      this.poiSvc.updatePoint(this.editingPoi()!.id!, {
        name:        data.name,
        category:    data.category,
        description: data.description,
      });
    } else {
      const coords = this.pendingCoords() ??
        (data.lat && data.lng
          ? { lat: parseFloat(data.lat), lng: parseFloat(data.lng) }
          : null);
      if (coords && !isNaN(coords.lat) && !isNaN(coords.lng)) {
        this.poiSvc.addPoint(coords, data.name, data.category, data.description);
      }
    }
    this.onModalClose();
  }

  onImportReportDismissed(): void {
    this.importResult.set(null);
  }

  toggleSidebar(): void {
    this.sidebarCollapsed.update(v => !v);
  }
}

<div class="app-shell">
  <ds-top-bar
    [search]="search()"
    (searchChange)="onSearchChange($event)"
    [canUndo]="poiSvc.canUndo()"
    [canRedo]="poiSvc.canRedo()"
    (undo)="onUndo()"
    (redo)="onRedo()"
    (clearAll)="onClearAll()"
    (import)="onImport($event)"
    (export)="onExport()"
  />

  <app-import-report
    [result]="importResult()"
    (dismissed)="onImportReportDismissed()"
  />

  <div class="app-body">
    <ds-sidebar
      [pois]="mappedPois()"
      [categories]="SIDEBAR_CATEGORIES"
      [collapsed]="sidebarCollapsed()"
      (toggle)="toggleSidebar()"
      (new)="onNewPoi()"
      (edit)="onEditById($event)"
      (delete)="onDeletePoi($event)"
      (focus)="onFocusPoi($event)"
    />
    <app-map class="app-map" (mapClick)="onMapClick($event)" />
  </div>

  <ds-poi-form-modal
    [open]="showForm()"
    [initialData]="modalInitialData()"
    (close)="onModalClose()"
    (save)="onModalSave($event)"
  />
</div>
