// libs/design-system-react/src/components/Sidebar/Sidebar.tsx
import * as React from 'react';
import { Plus, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '../Button/Button';
import { POIItem, type POIItemProps } from '../POIItem/POIItem';
import { CategoryChip, type CategoryId } from '../CategoryChip/CategoryChip';
import styles from './Sidebar.module.css';

export interface SidebarCategory {
  id:    CategoryId;
  label: string;
}

export type SidebarPOI = Omit<POIItemProps, 'onEdit' | 'onDelete' | 'onClick'>;

export interface SidebarProps {
  pois:        SidebarPOI[];
  categories:  SidebarCategory[];
  collapsed:   boolean;
  onToggle:    () => void;
  onNew:       () => void;
  onEdit:      (id: string) => void;
  onDelete:    (id: string) => void;
  onFocus:     (id: string) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({
  pois, categories, collapsed,
  onToggle, onNew, onEdit, onDelete, onFocus,
}) => (
  <aside
    className={styles.sidebar}
    aria-label="POI list"
    aria-expanded={!collapsed}
    style={{ width: collapsed ? 0 : 'var(--ds-sidebar-width)' }}
  >
    {/* Toggle */}
    <button
      type="button"
      className={styles.toggle}
      onClick={onToggle}
      aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
    >
      {collapsed
        ? <ChevronRight className={styles.toggleIcon} aria-hidden="true" />
        : <ChevronLeft  className={styles.toggleIcon} aria-hidden="true" />
      }
    </button>

    {!collapsed && (
      <div className={styles.inner}>
        {/* New POI */}
        <div className={styles.newBtnWrapper}>
          <Button variant="primary" size="md" className={styles.newBtn} onClick={onNew}>
            <Plus aria-hidden="true" />
            New POI
          </Button>
        </div>

        {/* Section header */}
        <div className={styles.sectionHeader}>
          <h2 className={styles.sectionLabel}>POIs</h2>
          <span className={styles.sectionCount} aria-live="polite">
            {pois.length}
          </span>
        </div>

        {/* POI list */}
        <div role="list" className={styles.list}>
          {pois.length === 0 ? (
            <div className={styles.emptyState}>
              No points yet.<br />Click the map or "New POI".
            </div>
          ) : (
            <div className={styles.listItems}>
              {pois.map(poi => (
                <POIItem
                  key={poi.id} {...poi}
                  onEdit={onEdit}
                  onDelete={onDelete}
                  onClick={onFocus}
                />
              ))}
            </div>
          )}
        </div>

        {/* Categories */}
        <div className={styles.categories}>
          <h2 className={styles.sectionLabel}>Categories</h2>
          <div className={styles.chips}>
            {categories.map(cat => (
              <CategoryChip key={cat.id} category={cat.id} label={cat.label} />
            ))}
          </div>
        </div>
      </div>
    )}
  </aside>
);
Sidebar.displayName = 'Sidebar';

// libs/design-system-angular/src/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';
import { NgIf, NgFor, CommonModule } from '@angular/common';
import { DsButtonComponent } from '../button/button.component';
import { DsPoiItemComponent } from '../poi-item/poi-item.component';
import { DsCategoryChipComponent } from '../category-chip/category-chip.component';
import { DsIconComponent } from '../icon/icon.component';
import type { SidebarPoi, SidebarCategory } from '../../utils/category-types';

@Component({
  selector: 'ds-sidebar',
  standalone: true,
  imports: [NgIf, NgFor, CommonModule, DsButtonComponent, DsPoiItemComponent, DsCategoryChipComponent, DsIconComponent],
  template: `
    <aside
      class="sidebar"
      [style.width]="collapsed ? '0' : 'var(--ds-sidebar-width)'"
      aria-label="POI list"
      [attr.aria-expanded]="!collapsed"
    >
      <button
        type="button"
        class="toggle"
        (click)="toggle.emit()"
        [attr.aria-label]="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
      >
        <ds-icon
          [name]="collapsed ? 'chevron-right' : 'chevron-left'"
          [size]="16"
          class="toggleIcon"
          aria-hidden="true"
        />
      </button>

      <div class="inner" *ngIf="!collapsed">
        <div class="newBtnWrapper">
          <ds-button variant="primary" size="md" class="newBtn" (click)="new.emit()">
            <ds-icon name="plus" [size]="16" aria-hidden="true" />
            New POI
          </ds-button>
        </div>

        <div class="sectionHeader">
          <h2 class="sectionLabel">POIs</h2>
          <span class="sectionCount" aria-live="polite">
            {{ pois.length }}
          </span>
        </div>

        <div role="list" class="list">
          <div *ngIf="pois.length === 0" class="emptyState">
            No points yet.<br />Click the map or "New POI".
          </div>
          <div class="listItems" *ngIf="pois.length > 0">
            <ds-poi-item
              *ngFor="let poi of pois"
              [id]="poi.id"
              [name]="poi.name"
              [category]="poi.category"
              [lat]="poi.lat"
              [lng]="poi.lng"
              [selected]="poi.selected ?? false"
              (onClick)="focus.emit($event)"
              (edit)="edit.emit($event)"
              (delete)="delete.emit($event)"
            />
          </div>
        </div>

        <div class="categories">
          <h2 class="sectionLabel">Categories</h2>
          <div class="chips">
            <ds-category-chip
              *ngFor="let cat of categories"
              [category]="cat.id"
              [label]="cat.label"
            />
          </div>
        </div>
      </div>
    </aside>
  `,
  styleUrls: ['./sidebar.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class DsSidebarComponent {
  @Input() pois: SidebarPoi[] = [];
  @Input() categories: SidebarCategory[] = [];
  @Input() collapsed = false;

  @Output() toggle = new EventEmitter<void>();
  @Output() new = new EventEmitter<void>();
  @Output() edit = new EventEmitter<string>();
  @Output() delete = new EventEmitter<string>();
  @Output() focus = new EventEmitter<string>();
}
