// libs/design-system-angular/src/components/select/select.component.ts
import { Component, Input, ViewEncapsulation, forwardRef, computed } from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { DsIconComponent } from '../icon/icon.component';
import type { SelectOption } from '../../utils/category-types';

@Component({
  selector: 'ds-select',
  standalone: true,
  imports: [NgIf, NgFor, DsIconComponent],
  template: `
    <div class="wrapper">
      <span
        *ngIf="selectedOption()?.colorVar"
        class="colorDot"
        [style.background]="selectedOption()?.colorVar"
        aria-hidden="true"
      ></span>
      <select
        [id]="id"
        [class.withDot]="selectedOption()?.colorVar"
        [class.hasError]="error"
        [value]="value"
        [disabled]="isDisabled"
        (change)="onChange($event)"
        (blur)="onTouched()"
        class="select"
      >
        <option *ngFor="let opt of options" [value]="opt.value">
          {{ opt.label }}
        </option>
      </select>
      <ds-icon name="chevron-down" [size]="16" class="chevron" aria-hidden="true" />
      <p *ngIf="error" role="alert" class="errorMessage">{{ error }}</p>
    </div>
  `,
  styleUrls: ['./select.component.css'],
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => DsSelectComponent),
      multi: true,
    },
  ],
})
export class DsSelectComponent implements ControlValueAccessor {
  @Input() id?: string;
  @Input() options: SelectOption[] = [];
  @Input() error?: string;

  value = '';
  isDisabled = false;

  selectedOption = computed(() => this.options.find(o => o.value === this.value));

  private onChangeCallback: (value: string) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  writeValue(value: any): void {
    this.value = value ?? '';
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.isDisabled = isDisabled;
  }

  onChange(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.value = target.value;
    this.onChangeCallback(this.value);
  }

  onTouched(): void {
    this.onTouchedCallback();
  }
}

// libs/design-system-react/src/components/Select/Select.tsx
import * as React from 'react';
import { ChevronDown } from 'lucide-react';
import { cn } from '../../utils/cn';
import styles from './Select.module.css';

export interface SelectOption {
  value: string;
  label: string;
  colorVar?: string;
}

export interface SelectProps extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, 'children'> {
  options:  SelectOption[];
  error?:   string;
}

export const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
  ({ options, error, className, id, ...props }, ref) => {
    const errorId = error && id ? `${id}-error` : undefined;
    const selected = options.find(o => o.value === props.value);
    return (
      <div className={styles.wrapper}>
        {/* Active option color dot */}
        {selected?.colorVar && (
          <span
            className={styles.colorDot}
            style={{ background: selected.colorVar }}
            aria-hidden="true"
          />
        )}
        <select
          ref={ref} id={id}
          aria-describedby={errorId}
          aria-invalid={!!error || undefined}
          className={cn(
            styles.select,
            selected?.colorVar && styles.withDot,
            error && styles.hasError,
            className,
          )}
          {...props}
        >
          {options.map(opt => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
        <ChevronDown className={styles.chevron} aria-hidden="true" />
        {error && <p id={errorId} role="alert" className={styles.errorMessage}>{error}</p>}
      </div>
    );
  },
);
Select.displayName = 'Select';
