// libs/design-system-react/src/components/Button/Button.tsx
import * as React from 'react';
import { cn } from '../../utils/cn';
import styles from './Button.module.css';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive' | 'outline';
export type ButtonSize    = 'sm' | 'md' | 'lg' | 'icon';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?:    ButtonSize;
  loading?: boolean;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = 'primary', size = 'md', loading = false, className, children, disabled, ...props }, ref) => (
    <button
      ref={ref}
      className={cn(styles.button, styles[`variant-${variant}`], styles[`size-${size}`], loading && styles.loading, className)}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...props}
    >
      {loading && <span className={styles.spinner} aria-hidden="true" />}
      {children}
    </button>
  ),
);
Button.displayName = 'Button';

// libs/design-system-angular/src/components/button/button.component.ts
import { Component, Input, ViewEncapsulation, computed, HostBinding } from '@angular/core';
import { NgIf, CommonModule } from '@angular/common';

@Component({
  selector: 'ds-button',
  standalone: true,
  imports: [NgIf, CommonModule],
  template: `
    <button
      [class]="hostClass()"
      [disabled]="disabled || loading"
      [attr.aria-busy]="loading || null"
      type="button"
    >
      <span *ngIf="loading" class="spinner" aria-hidden="true"></span>
      <ng-content></ng-content>
    </button>
  `,
  styleUrls: ['./button.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class DsButtonComponent {
  @Input() variant: 'primary' | 'secondary' | 'ghost' | 'destructive' | 'outline' = 'primary';
  @Input() size: 'sm' | 'md' | 'lg' | 'icon' = 'md';
  @Input() loading = false;
  @Input() disabled = false;

  @HostBinding('attr.class') get attrClass(): string {
    // This allows classes passed to ds-button to be inherited by :host
    return '';
  }

  hostClass = computed(() => {
    const classes = ['button', `variant-${this.variant}`, `size-${this.size}`];
    if (this.loading) classes.push('loading');
    return classes.join(' ');
  });
}
