// apps/angular-app/src/app/shared/components/import-report/import-report.component.ts
import { Component, input, output } from '@angular/core';
import type { ImportResult } from '@geo-editor/core';

@Component({
  selector: 'app-import-report',
  standalone: true,
  template: `
    @if (result(); as r) {
      <div class="import-report" [class.import-report--has-errors]="r.errors.length > 0">
        <p class="import-report__summary">{{ r.summary }}</p>

        @if (r.errors.length > 0) {
          <details class="import-report__details">
            <summary>Ver detalle de errores ({{ r.errors.length }})</summary>
            <ul>
              @for (err of r.errors; track err.index) {
                <li>Feature #{{ err.index }}: {{ err.message }}</li>
              }
            </ul>
          </details>
        }

        <button class="btn btn-secondary import-report__close" (click)="dismissed.emit()">
          ✕ Cerrar
        </button>
      </div>
    }
  `,
})
export class ImportReportComponent {
  readonly result    = input<ImportResult | null>(null);
  readonly dismissed = output<void>();
}

// apps/react-app/src/components/ImportReport.tsx
import type { ImportResult } from '@geo-editor/core';

interface ImportReportProps {
  result:    ImportResult | null;
  onDismiss: () => void;
}

export function ImportReport({ result, onDismiss }: ImportReportProps) {
  if (!result) return null;

  return (
    <div className={`import-report${result.errors.length > 0 ? ' import-report--has-errors' : ''}`}>
      <p className="import-report__summary">{result.summary}</p>

      {result.errors.length > 0 && (
        <details className="import-report__details">
          <summary>Ver detalle de errores ({result.errors.length})</summary>
          <ul>
            {result.errors.map((err) => (
              <li key={err.index}>Feature #{err.index}: {err.message}</li>
            ))}
          </ul>
        </details>
      )}

      <button className="btn btn-secondary import-report__close" onClick={onDismiss}>
        ✕ Cerrar
      </button>
    </div>
  );
}
