// apps/angular-app/src/app/features/poi-form/poi-form.component.ts
import { Component, inject, input, output, OnChanges } from '@angular/core';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { NgFor, NgIf } from '@angular/common';
import type { PoiFeature, LngLat } from '@geo-editor/core';

@Component({
  selector: 'app-poi-form',
  templateUrl: './poi-form.component.html',
  imports: [ReactiveFormsModule, NgFor, NgIf],
  standalone: true,
})
export class PoiFormComponent implements OnChanges {
  private readonly fb = inject(FormBuilder);

  readonly poi        = input<PoiFeature | null>(null);
  readonly coords     = input<LngLat | null>(null);
  readonly saved      = output<{ name: string; category: string }>();
  readonly cancelled  = output<void>();

  readonly CATEGORIES = [
    'landmark', 'park', 'restaurant', 'hotel',
    'shop', 'transport', 'cafe', 'museum',
    'health', 'education', 'other',
  ];

  form = this.fb.group({
    name:     ['', [Validators.required, Validators.minLength(2)]],
    category: ['', Validators.required],
  });

  get isEditing(): boolean { return !!this.poi(); }

  ngOnChanges(): void {
    const p = this.poi();
    if (p) {
      this.form.patchValue({ name: p.properties.name, category: p.properties.category });
    } else {
      this.form.reset();
    }
  }

  onSubmit(): void {
    if (this.form.valid) {
      this.saved.emit(this.form.value as { name: string; category: string });
      this.form.reset();
    }
  }

  onCancel(): void {
    this.form.reset();
    this.cancelled.emit();
  }
}

<div class="poi-form" [formGroup]="form">
  <h4>{{ isEditing ? 'Editar POI' : 'Nuevo POI' }}</h4>

  @if (coords() && !isEditing) {
    <p class="poi-form__coords">
      📍 {{ coords()!.lng.toFixed(5) }}, {{ coords()!.lat.toFixed(5) }}
    </p>
  }

  <div class="form-group">
    <label for="poi-name">Nombre *</label>
    <input
      id="poi-name"
      type="text"
      formControlName="name"
      placeholder="Nombre del POI"
      class="form-control"
      [class.is-invalid]="form.controls.name.invalid && form.controls.name.touched"
    />
    @if (form.controls.name.invalid && form.controls.name.touched) {
      <span class="error-msg">Mínimo 2 caracteres</span>
    }
  </div>

  <div class="form-group">
    <label for="poi-category">Categoría *</label>
    <select id="poi-category" formControlName="category" class="form-control">
      <option value="" disabled>Seleccionar categoría</option>
      @for (cat of CATEGORIES; track cat) {
        <option [value]="cat">{{ cat }}</option>
      }
    </select>
    @if (form.controls.category.invalid && form.controls.category.touched) {
      <span class="error-msg">Selecciona una categoría</span>
    }
  </div>

  <div class="poi-form__actions">
    <button class="btn btn-primary" (click)="onSubmit()" [disabled]="form.invalid">
      {{ isEditing ? '💾 Guardar' : '➕ Agregar' }}
    </button>
    <button class="btn btn-secondary" (click)="onCancel()">Cancelar</button>
  </div>
</div>

// apps/react-app/src/components/PoiForm.tsx
import { useState, useEffect } from 'react';
import { usePoiStore } from '../store/poi.store';
import type { PoiFeature, LngLat } from '@geo-editor/core';

const CATEGORIES = [
  'landmark', 'park', 'restaurant', 'hotel',
  'shop', 'transport', 'cafe', 'museum',
  'health', 'education', 'other',
];

interface PoiFormProps {
  poi:       PoiFeature | null;
  coords:    LngLat | null;
  onSaved:   () => void;
  onCancel:  () => void;
}

export function PoiForm({ poi, coords, onSaved, onCancel }: PoiFormProps) {
  const { addPoint, updatePoint } = usePoiStore();
  const [name, setName]         = useState('');
  const [category, setCategory] = useState('');
  const [touched, setTouched]   = useState(false);

  useEffect(() => {
    if (poi) {
      setName(poi.properties.name);
      setCategory(poi.properties.category);
    } else {
      setName('');
      setCategory('');
    }
    setTouched(false);
  }, [poi]);

  const isValid = name.trim().length >= 2 && category !== '';

  function handleSubmit() {
    setTouched(true);
    if (!isValid) return;

    if (poi) {
      updatePoint(poi.id!, { name: name.trim(), category });
    } else if (coords) {
      addPoint(coords, name.trim(), category);
    }
    onSaved();
  }

  return (
    <div className="poi-form">
      <h4>{poi ? 'Editar POI' : 'Nuevo POI'}</h4>

      {coords && !poi && (
        <p className="poi-form__coords">
          📍 {coords.lng.toFixed(5)}, {coords.lat.toFixed(5)}
        </p>
      )}

      <div className="form-group">
        <label htmlFor="r-poi-name">Nombre *</label>
        <input
          id="r-poi-name"
          type="text"
          className={`form-control${touched && name.trim().length < 2 ? ' is-invalid' : ''}`}
          placeholder="Nombre del POI"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        {touched && name.trim().length < 2 && (
          <span className="error-msg">Mínimo 2 caracteres</span>
        )}
      </div>

      <div className="form-group">
        <label htmlFor="r-poi-category">Categoría *</label>
        <select
          id="r-poi-category"
          className={`form-control${touched && !category ? ' is-invalid' : ''}`}
          value={category}
          onChange={(e) => setCategory(e.target.value)}
        >
          <option value="" disabled>Seleccionar categoría</option>
          {CATEGORIES.map((cat) => (
            <option key={cat} value={cat}>{cat}</option>
          ))}
        </select>
        {touched && !category && (
          <span className="error-msg">Selecciona una categoría</span>
        )}
      </div>

      <div className="poi-form__actions">
        <button className="btn btn-primary" onClick={handleSubmit} disabled={touched && !isValid}>
          {poi ? '💾 Guardar' : '➕ Agregar'}
        </button>
        <button className="btn btn-secondary" onClick={onCancel}>Cancelar</button>
      </div>
    </div>
  );
}
