// apps/angular-app/src/app/features/toolbar/toolbar.component.ts
import { Component, inject, output } from '@angular/core';
import { FileIoService } from '../../core/services/file-io.service';
import { PoiService } from '../../core/services/poi.service';
import type { ImportResult } from '@geo-editor/core';

@Component({
  selector: 'app-toolbar',
  standalone: true,
  templateUrl: './toolbar.component.html',
})
export class ToolbarComponent {
  readonly poiSvc = inject(PoiService);
  private readonly fileIo = inject(FileIoService);

  readonly importDone = output<ImportResult>();

  async onFileSelected(event: Event): Promise<void> {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    try {
      const result = await this.fileIo.importGeoJson(file);
      if (result.imported.length > 0) {
        this.poiSvc.loadCollection({
          type: 'FeatureCollection',
          features: [...this.poiSvc.collection().features, ...result.imported],
        });
      }
      this.importDone.emit(result);
    } catch (err) {
      console.error('Import failed:', err);
    }
    (event.target as HTMLInputElement).value = '';
  }

  onExport(): void {
    this.fileIo.exportGeoJson(this.poiSvc.collection());
  }

  async onClear(): Promise<void> {
    if (confirm('¿Borrar todos los puntos y reiniciar?')) {
      await this.poiSvc.clearAll();
    }
  }
}

<div class="toolbar">
  <label class="btn btn-primary" for="file-input">
    📂 Importar GeoJSON
  </label>
  <input
    id="file-input"
    type="file"
    accept=".geojson,.json"
    (change)="onFileSelected($event)"
    hidden
  />

  <button class="btn btn-secondary" (click)="onExport()">
    💾 Exportar GeoJSON
  </button>

  <!-- Undo / Redo -->
  <button
    class="btn btn-secondary"
    (click)="poiSvc.undo()"
    [disabled]="!poiSvc.canUndo()"
    title="Deshacer (Ctrl+Z)">
    ↩ Deshacer
  </button>
  <button
    class="btn btn-secondary"
    (click)="poiSvc.redo()"
    [disabled]="!poiSvc.canRedo()"
    title="Rehacer (Ctrl+Y)">
    ↪ Rehacer
  </button>

  <button class="btn btn-danger" (click)="onClear()">
    🗑 Limpiar todo
  </button>
</div>

// apps/react-app/src/components/Toolbar.tsx
import { useRef } from 'react';
import { usePoiStore } from '../store/poi.store';
import { useFileIo } from '../hooks/useFileIo';
import type { ImportResult } from '@geo-editor/core';

interface ToolbarProps {
  onImportDone: (result: ImportResult) => void;
}

export function Toolbar({ onImportDone }: ToolbarProps) {
  const { collection, loadCollection, clearAll, undo, redo, canUndo, canRedo } = usePoiStore();
  const { importGeoJson, exportGeoJson } = useFileIo();
  const inputRef = useRef<HTMLInputElement>(null);

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const result = await importGeoJson(file);
      if (result.imported.length > 0) {
        loadCollection({ type: 'FeatureCollection', features: [...collection().features, ...result.imported] });
      }
      onImportDone(result);
    } catch (err) {
      console.error('Import failed:', err);
    }
    if (inputRef.current) inputRef.current.value = '';
  }

  async function handleClear() {
    if (confirm('¿Borrar todos los puntos y reiniciar?')) {
      await clearAll();
    }
  }

  return (
    <div className="toolbar">
      <label className="btn btn-primary" htmlFor="file-input">
        📂 Importar GeoJSON
      </label>
      <input
        id="file-input"
        ref={inputRef}
        type="file"
        accept=".geojson,.json"
        onChange={handleFileChange}
        style={{ display: 'none' }}
      />
      <button className="btn btn-secondary" onClick={() => exportGeoJson(collection())}>
        💾 Exportar GeoJSON
      </button>

      <button className="btn btn-secondary" onClick={undo} disabled={!canUndo()} title="Deshacer (Ctrl+Z)">
        ↩ Deshacer
      </button>
      <button className="btn btn-secondary" onClick={redo} disabled={!canRedo()} title="Rehacer (Ctrl+Y)">
        ↪ Rehacer
      </button>

      <button className="btn btn-danger" onClick={handleClear}>
        🗑 Limpiar todo
      </button>
    </div>
  );
}
