// apps/react-app/src/components/PoiList.tsx
import { useState } from 'react';
import { usePoiStore } from '../store/poi.store';
import type { PoiFeature } from '@geo-editor/core';

interface PoiListProps {
  onEditRequest: (poi: PoiFeature) => void;
  onFlyTo:       (lng: number, lat: number) => void;
}

export function PoiList({ onEditRequest, onFlyTo }: PoiListProps) {
  const { collection, selectedId, selectPoint, removePoint, setFilter, filteredFeatures } = usePoiStore();
  const [query, setQuery] = useState('');

  function handleSearch(e: React.ChangeEvent<HTMLInputElement>) {
    setQuery(e.target.value);
    setFilter({ query: e.target.value });
  }

  function handleSelect(poi: PoiFeature) {
    selectPoint(poi.id ?? null);
    onFlyTo(poi.geometry.coordinates[0], poi.geometry.coordinates[1]);
  }

  function handleDelete(poi: PoiFeature) {
    if (confirm(`¿Eliminar "${poi.properties.name}"?`)) {
      removePoint(poi.id!);
    }
  }

  const visible = filteredFeatures();

  return (
    <div className="poi-list">
      <div className="poi-list__header">
        <h3>POIs <span className="badge">{collection().features.length}</span></h3>
        <input
          className="search-input"
          type="text"
          placeholder="Buscar por nombre..."
          value={query}
          onChange={handleSearch}
        />
      </div>

      {visible.length === 0 && (
        <p className="poi-list__empty">
          {collection().features.length === 0
            ? 'No hay POIs. Haz clic en el mapa para agregar.'
            : `Sin resultados para "${query}".`}
        </p>
      )}

      <ul className="poi-list__items">
        {visible.map((poi) => (
          <li
            key={poi.id}
            className={`poi-item${selectedId === poi.id ? ' poi-item--selected' : ''}`}
            onClick={() => handleSelect(poi)}
          >
            <div className="poi-item__info">
              <span className="poi-item__name">{poi.properties.name}</span>
              <span className="poi-item__category">{poi.properties.category}</span>
            </div>
            <div className="poi-item__actions">
              <button
                className="btn-icon"
                title="Editar"
                onClick={(e) => { e.stopPropagation(); onEditRequest(poi); }}
              >✏️</button>
              <button
                className="btn-icon btn-icon--danger"
                title="Eliminar"
                onClick={(e) => { e.stopPropagation(); handleDelete(poi); }}
              >🗑</button>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

// apps/angular-app/src/app/features/poi-list/poi-list.component.ts
import { Component, inject, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgFor, NgIf } from '@angular/common';
import { PoiService } from '../../core/services/poi.service';
import { MapService } from '../../core/services/map.service';
import type { PoiFeature } from '@geo-editor/core';

@Component({
  selector: 'app-poi-list',
  templateUrl: './poi-list.component.html',
  imports: [FormsModule, NgFor, NgIf],
  standalone: true,
})
export class PoiListComponent {
  readonly poiSvc    = inject(PoiService);
  readonly mapSvc    = inject(MapService);

  readonly editRequest = output<PoiFeature>();

  searchQuery = '';

  onSearch(): void {
    this.poiSvc.setFilter({ query: this.searchQuery });
  }

  onSelect(poi: PoiFeature): void {
    this.poiSvc.selectPoint(poi.id ?? null);
    this.mapSvc.flyTo(poi.geometry.coordinates[0], poi.geometry.coordinates[1]);
  }

  onEdit(poi: PoiFeature): void {
    this.editRequest.emit(poi);
  }

  onDelete(poi: PoiFeature): void {
    if (confirm(`¿Eliminar "${poi.properties.name}"?`)) {
      this.poiSvc.removePoint(poi.id!);
    }
  }

  trackById(_index: number, poi: PoiFeature): string | number {
    return poi.id ?? _index;
  }
}

<div class="poi-list">
  <div class="poi-list__header">
    <h3>POIs <span class="badge">{{ poiSvc.features().length }}</span></h3>
    <input
      class="search-input"
      type="text"
      placeholder="Buscar por nombre..."
      [(ngModel)]="searchQuery"
      (input)="onSearch()"
    />
  </div>

  @if (poiSvc.filteredFeatures().length === 0) {
    <p class="poi-list__empty">
      {{ poiSvc.features().length === 0 ? 'No hay POIs. Haz clic en el mapa para agregar.' : 'Sin resultados para "' + searchQuery + '".' }}
    </p>
  }

  <ul class="poi-list__items">
    @for (poi of poiSvc.filteredFeatures(); track trackById($index, poi)) {
      <li
        class="poi-item"
        [class.poi-item--selected]="poiSvc.selectedId() === poi.id"
        (click)="onSelect(poi)"
      >
        <div class="poi-item__info">
          <span class="poi-item__name">{{ poi.properties.name }}</span>
          <span class="poi-item__category">{{ poi.properties.category }}</span>
        </div>
        <div class="poi-item__actions">
          <button class="btn-icon" title="Editar" (click)="onEdit(poi); $event.stopPropagation()">✏️</button>
          <button class="btn-icon btn-icon--danger" title="Eliminar" (click)="onDelete(poi); $event.stopPropagation()">🗑</button>
        </div>
      </li>
    }
  </ul>
</div>
