// libs/design-system-react/src/components/POIItem/POIItem.tsx
import * as React from 'react';
import { Pencil, Trash2 } from 'lucide-react';
import { cn } from '../../utils/cn';
import { CATEGORY_COLORS, type CategoryId } from '../CategoryChip/CategoryChip';
import styles from './POIItem.module.css';

export interface POIItemProps {
  id:        string;
  name:      string;
  category:  CategoryId;
  icon:      React.ElementType;
  lat:       number;
  lng:       number;
  onEdit?:   (id: string) => void;
  onDelete?: (id: string) => void;
  onClick?:  (id: string) => void;
  className?: string;
  selected?: boolean;
}

export const POIItem: React.FC<POIItemProps> = ({
  id, name, category, icon: Icon, lat, lng,
  onEdit, onDelete, onClick, className, selected,
}) => {
  const color = CATEGORY_COLORS[category];

  return (
    <div
      role="listitem"
      tabIndex={0}
      className={cn(styles.item, selected && styles.selected, className)}
      onClick={() => onClick?.(id)}
      onKeyDown={e => e.key === 'Enter' && onClick?.(id)}
      aria-label={`${name}, ${category}`}
    >
      {/* Icon badge */}
      <div
        className={styles.iconBadge}
        style={{ background: `color-mix(in oklab, ${color} 18%, transparent)` }}
        aria-hidden="true"
      >
        <Icon className={styles.icon} style={{ color }} />
      </div>

      {/* Content */}
      <div className={styles.content}>
        <p className={styles.name}>{name}</p>
        <p className={styles.coords}>
          {lat.toFixed(4)}, {lng.toFixed(4)}
        </p>
      </div>

      {/* Actions */}
      {(onEdit || onDelete) && (
        <div className={styles.actions} aria-label="Actions">
          {onEdit && (
            <button
              type="button"
              className={cn(styles.actionBtn, styles.editBtn)}
              onClick={e => { e.stopPropagation(); onEdit(id); }}
              aria-label={`Edit ${name}`}
            >
              <Pencil className={styles.actionIcon} />
            </button>
          )}
          {onDelete && (
            <button
              type="button"
              className={cn(styles.actionBtn, styles.deleteBtn)}
              onClick={e => { e.stopPropagation(); onDelete(id); }}
              aria-label={`Delete ${name}`}
            >
              <Trash2 className={styles.actionIcon} />
            </button>
          )}
        </div>
      )}
    </div>
  );
};
POIItem.displayName = 'POIItem';

// libs/design-system-angular/src/components/poi-item/poi-item.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation, computed, HostListener } from '@angular/core';
import { NgIf } from '@angular/common';
import { DecimalPipe } from '@angular/common';
import { DsIconComponent } from '../icon/icon.component';
import type { CategoryId, IconName } from '../../utils/category-types';
import { CATEGORY_COLORS } from '../../utils/category-types';

const CATEGORY_ICONS: Record<CategoryId, IconName> = {
  restaurant: 'utensils',
  hotel:      'hotel',
  park:       'trees',
  hospital:   'cross',
  custom:     'map-pin',
};

@Component({
  selector: 'ds-poi-item',
  standalone: true,
  imports: [NgIf, DecimalPipe, DsIconComponent],
  template: `
    <div
      role="listitem"
      [attr.tabindex]="0"
      [class.item]="true"
      [class.selected]="selected"
      [attr.aria-label]="name + ', ' + category"
      (click)="onClick.emit(id)"
      (keydown)="onKeyDown($event)"
    >
      <div
        class="iconBadge"
        [style.background]="badgeBackground()"
        aria-hidden="true"
      >
        <ds-icon [name]="iconName()" class="icon" [style.color]="color()" />
      </div>

      <div class="content">
        <p class="name">{{ name }}</p>
        <p class="coords">
          {{ lat | number: '1.4-4' }}, {{ lng | number: '1.4-4' }}
        </p>
      </div>

      <div class="actions" *ngIf="edit || delete" [attr.aria-label]="'Actions'">
        <button
          *ngIf="edit"
          type="button"
          class="actionBtn editBtn"
          [attr.aria-label]="'Edit ' + name"
          (click)="stopPropagationAndEmit($event, 'edit')"
        >
          <ds-icon name="pencil" class="actionIcon" />
        </button>
        <button
          *ngIf="delete"
          type="button"
          class="actionBtn deleteBtn"
          [attr.aria-label]="'Delete ' + name"
          (click)="stopPropagationAndEmit($event, 'delete')"
        >
          <ds-icon name="trash2" class="actionIcon" />
        </button>
      </div>
    </div>
  `,
  styleUrls: ['./poi-item.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class DsPoiItemComponent {
  @Input() id!: string;
  @Input() name!: string;
  @Input() category!: CategoryId;
  @Input() lat!: number;
  @Input() lng!: number;
  @Input() selected = false;

  @Output() onClick = new EventEmitter<string>();
  @Output() edit = new EventEmitter<string>();
  @Output() delete = new EventEmitter<string>();

  color = computed(() => CATEGORY_COLORS[this.category]);
  iconName = computed(() => CATEGORY_ICONS[this.category]);
  badgeBackground = computed(() => {
    const color = this.color();
    return `color-mix(in oklab, ${color} 18%, transparent)`;
  });

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.onClick.emit(this.id);
    }
  }

  stopPropagationAndEmit(event: Event, action: 'edit' | 'delete'): void {
    event.stopPropagation();
    if (action === 'edit') {
      this.edit.emit(this.id);
    } else {
      this.delete.emit(this.id);
    }
  }
}
