// libs/design-system-react/src/components/CategoryChip/CategoryChip.tsx
import * as React from 'react';
import { cn } from '../../utils/cn';
import styles from './CategoryChip.module.css';

export type CategoryId = 'restaurant' | 'hotel' | 'park' | 'hospital' | 'custom';

export const CATEGORY_COLORS: Record<CategoryId, string> = {
  restaurant: 'var(--ds-cat-restaurant)',
  hotel:      'var(--ds-cat-hotel)',
  park:       'var(--ds-cat-park)',
  hospital:   'var(--ds-cat-hospital)',
  custom:     'var(--ds-cat-custom)',
};

export interface CategoryChipProps {
  category:     CategoryId;
  label:        string;
  interactive?: boolean;
  active?:      boolean;
  onClick?:     () => void;
  className?:   string;
}

export const CategoryChip: React.FC<CategoryChipProps> = ({
  category, label, interactive = false, active = false, onClick, className,
}) => {
  const color = CATEGORY_COLORS[category];

  const style: React.CSSProperties = {
    background:  active
      ? `color-mix(in oklab, ${color} 25%, transparent)`
      : `color-mix(in oklab, ${color} 12%, transparent)`,
    borderColor: `color-mix(in oklab, ${color} 35%, transparent)`,
    color:       `color-mix(in oklab, ${color} 75%, var(--ds-foreground))`,
  };

  if (interactive) {
    return (
      <button
        type="button"
        onClick={onClick}
        aria-pressed={active}
        style={style}
        className={cn(styles.chip, styles.interactive, active && styles.active, className)}
      >
        <span className={styles.dot} style={{ background: color }} aria-hidden="true" />
        {label}
      </button>
    );
  }

  return (
    <span style={style} className={cn(styles.chip, className)}>
      <span className={styles.dot} style={{ background: color }} aria-hidden="true" />
      {label}
    </span>
  );
};
CategoryChip.displayName = 'CategoryChip';

// libs/design-system-angular/src/components/category-chip/category-chip.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation, computed } from '@angular/core';
import { NgIf } from '@angular/common';
import type { CategoryId } from '../../utils/category-types';
import { CATEGORY_COLORS } from '../../utils/category-types';

@Component({
  selector: 'ds-category-chip',
  standalone: true,
  imports: [NgIf],
  template: `
    <button
      *ngIf="interactive; else staticChip"
      type="button"
      [style]="chipStyle()"
      [class.chip]="true"
      [class.interactive]="true"
      [class.active]="active"
      [attr.aria-pressed]="active"
      (click)="chipClick.emit()"
    >
      <span class="dot" [style.background]="CATEGORY_COLORS[category]" aria-hidden="true"></span>
      {{ label }}
    </button>

    <ng-template #staticChip>
      <span [style]="chipStyle()" class="chip">
        <span class="dot" [style.background]="CATEGORY_COLORS[category]" aria-hidden="true"></span>
        {{ label }}
      </span>
    </ng-template>
  `,
  styleUrls: ['./category-chip.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class DsCategoryChipComponent {
  @Input() category!: CategoryId;
  @Input() label!: string;
  @Input() interactive = false;
  @Input() active = false;
  @Output() chipClick = new EventEmitter<void>();

  CATEGORY_COLORS = CATEGORY_COLORS;

  chipStyle = computed(() => {
    const color = CATEGORY_COLORS[this.category];
    return {
      background: this.active
        ? `color-mix(in oklab, ${color} 25%, transparent)`
        : `color-mix(in oklab, ${color} 12%, transparent)`,
      borderColor: `color-mix(in oklab, ${color} 35%, transparent)`,
      color: `color-mix(in oklab, ${color} 75%, var(--ds-foreground))`,
    };
  });
}
